### ISSUE TITLE
Import Device List file

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#357]
**Is your feature request related to a problem? Please describe.**
In NRFU testing, a user can specify a device file for DUT information

**Describe the solution you'd like**
If user specifies a device list file, Nrfu_client module will attempt to open the device list file.  If there is an error the user will be reprompted to enter a device list filename.

Nrfu_client module will expect the device list file to be a text file with an IP address per line for DUTs.  This will be converted into a list and stored for later use.

Example device list file:
```
1.1.1.1
1.1.1.2
…
1.1.1.100
```

**Describe alternatives you've considered**

**Additional context**

**Comment by rewati-arista** [comment]
@kgrozis-arista can you confirm if what this issue is asking for is addressed in this 
PR https://github.com/aristanetworks/vane/pull/392. Here is the specific method in it: https://github.com/aristanetworks/vane/blob/d9b0bbf9afb03aecbe8010fbfbfc797f44f9d440/vane/nrfu_client.py#L88

If not let me know if I am missing any additional requirement in this method.
