### ISSUE TITLE
Generate test catalog

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#643]
**Is your feature request related to a problem? Please describe.**
Need new command line option (`--generate-test-catalog`) for generating a test catalog with all test cases.

**Describe the solution you'd like**
Vane will use the directory(s) inputted at the command to create a test case catalog.  Below is how this will be inputted:
```
vane --generate-test-catalog <test directory1> <test directory2> ... <test directoryN>
```
Vane will recurse the directories to find test_definition files and test_<name>.py files.  Recursion will be similar to `--generate-test-steps` command line option.

Vane will use a combination of the information in the test_definition files and test_<name>.py files to create the test catalog.  

The following information will be collected from test_definition files:
* test suite name(s): top-level `name` field
* test case name(s): low-level `name` field
* test id(s): low-level `test_id` field

The following information will be collected from test_<name>.py file for each test case:
* test case name: function name
* test case description: TD: within a docstring.  Do not include TD:
* test steps: TS: within a docstring.  Steps should be numerically iterated started with 1.  Do not include TS:

The information will be correlated between test_definition files and test_<name>.py to create the following test catalog dictionary:
- name: < test suite name >
   test_cases: 
   - name: < test case name >
   - test_id: < test case id >
   - test_description: < test case description >
   - test_steps: < test steps >
  
The test catalog dictionary should be outputted in directory vane is ran from as test_catalog.csv using the following format:
Header row: 
```
Test Suite,Test Case ID,Test Case,Description,Test Steps
```
Data rows:
```
<test suite name>,<test case id>,<test case name>,<test_description>,<test_steps>
```

**Comment by rewati-arista** [comment]
@kgrozis-arista Reads good 👍🏻, a few minor suggestions:

(1) Do we want to introduce the argument in the flag itself like --generate-test-catalog <path/to/test_dir> instead of making it read from test_dir field in definitions.yaml. This might make this feature available to use for people who do not deal with definitions file as such.

(2) I think we could transform --generate-test-steps functionality to do this instead if we dont really end up using the 
--generate-test-steps feature. Probably a question for Bob/Anand other customers who use Vane.

(3) Do we want to have test steps in our data row, the same problem about making the row too big? We could have a succinct catalog table without test steps and then have a section (appendix kind) below with test case name and test case steps?

**Comment by kgrozis-arista** [comment]
@rewati-arista (3) If you user does turn on word wrap in cells, the steps will be truncated to a single row height.   A user could expand row if they find it meaningful.  What's your thoughts?

**Comment by rewati-arista** [comment]
> @rewati-arista (3) If user does not turn on word wrap in cells, the steps will be truncated to a single row height. A user could expand row if they find it meaningful. What's your thoughts?

Thats perfect then, we could stick to that 👍🏻

**Comment by kgrozis-arista** [comment]
@rewati-arista (2) I don't think anyone uses `--generate-test-steps`.  I tried to, and I found it problematic.  I would be in favor of turning it into `--generate-test-catalog`

**Comment by grybak-arista** [comment]
I think this looks good, too. Also like the suggestion of using `--generate-test-catalog` in place of `--generate-test-steps`.

**Comment by rewati-arista** [comment]
Reopening since feature branch: https://github.com/aristanetworks/vane/pull/646 is yet to be merged
